// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/google/uuid"
)

// BulkInviteEnvironmentUsersParams is parameters of bulk_invite_environment_users operation.
type BulkInviteEnvironmentUsersParams struct {
	EnvironmentID uuid.UUID
}

// CreateEntityParams is parameters of create_entity operation.
type CreateEntityParams struct {
	Group     string
	Version   string
	Namespace string
	Plural    string
}

// CreateEntityRelationParams is parameters of create_entity_relation operation.
type CreateEntityRelationParams struct {
	Namespace string
}

// CreateEnvironmentUserParams is parameters of create_environment_user operation.
type CreateEnvironmentUserParams struct {
	EnvironmentID uuid.UUID
}

// DeleteChatParams is parameters of delete_chat operation.
type DeleteChatParams struct {
	ChatID string
}

// DeleteEntityParams is parameters of delete_entity operation.
type DeleteEntityParams struct {
	Group     string
	Version   string
	Kind      string
	Namespace string
	Name      string
}

// DeleteEntityDefinitionParams is parameters of delete_entity_definition operation.
type DeleteEntityDefinitionParams struct {
	DefinitionID uuid.UUID
}

// DeleteEntityRelationParams is parameters of delete_entity_relation operation.
type DeleteEntityRelationParams struct {
	Namespace string
}

// DeleteEnvironmentUserParams is parameters of delete_environment_user operation.
type DeleteEnvironmentUserParams struct {
	EnvironmentID uuid.UUID
	UserID        string
}

// DeleteMcpendpointParams is parameters of delete_mcpendpoint operation.
type DeleteMcpendpointParams struct {
	McpendpointID uuid.UUID
}

// DeleteModelParams is parameters of delete_model operation.
type DeleteModelParams struct {
	ModelName string
}

// DeleteModelproviderParams is parameters of delete_modelprovider operation.
type DeleteModelproviderParams struct {
	ProviderID uuid.UUID
}

// DeleteOAuthServiceParams is parameters of delete_oauth_service operation.
type DeleteOAuthServiceParams struct {
	ServiceID uuid.UUID
}

// GetChatParams is parameters of get_chat operation.
type GetChatParams struct {
	ChatID string
}

// GetChatMessagesParams is parameters of get_chat_messages operation.
type GetChatMessagesParams struct {
	ChatID string
	Limit  OptInt
	Offset OptInt
}

// GetChatsParams is parameters of get_chats operation.
type GetChatsParams struct {
	Offset OptInt
	Limit  OptInt
}

// GetEntitiesParams is parameters of get_entities operation.
type GetEntitiesParams struct {
	Name   OptString
	Label  OptString
	Limit  OptInt
	Offset OptInt
	// Comma-separated field selectors in format 'key=value', supports dot notation for nested properties.
	FieldSelector OptString
}

// GetEntityParams is parameters of get_entity operation.
type GetEntityParams struct {
	Group     string
	Version   string
	Kind      string
	Namespace string
	Name      string
}

// GetEnvironmentStatusParams is parameters of get_environment_status operation.
type GetEnvironmentStatusParams struct {
	EnvID uuid.UUID
}

// GetEnvironmentUserParams is parameters of get_environment_user operation.
type GetEnvironmentUserParams struct {
	EnvironmentID uuid.UUID
	UserID        string
}

// GetMcpendpointParams is parameters of get_mcpendpoint operation.
type GetMcpendpointParams struct {
	McpendpointID uuid.UUID
}

// GetModelParams is parameters of get_model operation.
type GetModelParams struct {
	ModelName string
}

// GetModelproviderParams is parameters of get_modelprovider operation.
type GetModelproviderParams struct {
	ProviderID uuid.UUID
}

// GetOAuthServiceParams is parameters of get_oauth_service operation.
type GetOAuthServiceParams struct {
	ServiceID uuid.UUID
}

// GetPendingInvitationsParams is parameters of get_pending_invitations operation.
type GetPendingInvitationsParams struct {
	EnvironmentID uuid.UUID
}

// InviteEnvironmentUserParams is parameters of invite_environment_user operation.
type InviteEnvironmentUserParams struct {
	EnvironmentID uuid.UUID
}

// ListEnvironmentUsersParams is parameters of list_environment_users operation.
type ListEnvironmentUsersParams struct {
	EnvironmentID uuid.UUID
}

// ListOAuthServicesParams is parameters of list_oauth_services operation.
type ListOAuthServicesParams struct {
	// Only return active services.
	ActiveOnly OptBool
}

// PostChatMessagesParams is parameters of post_chat_messages operation.
type PostChatMessagesParams struct {
	ChatID string
}

// PostClerkWebhookParams is parameters of post_clerk_webhook operation.
type PostClerkWebhookParams struct {
	SvixID        string
	SvixTimestamp string
	SvixSignature string
}

// PostStripeWebhookParams is parameters of post_stripe_webhook operation.
type PostStripeWebhookParams struct {
	StripeSignature string
}

// RevokeOAuthTokenParams is parameters of revoke_oauth_token operation.
type RevokeOAuthTokenParams struct {
	ServiceName string
}

// UpdateChatParams is parameters of update_chat operation.
type UpdateChatParams struct {
	ChatID string
}

// UpdateEnvironmentUserParams is parameters of update_environment_user operation.
type UpdateEnvironmentUserParams struct {
	EnvironmentID uuid.UUID
	UserID        string
}

// UpdateMcpendpointParams is parameters of update_mcpendpoint operation.
type UpdateMcpendpointParams struct {
	McpendpointID uuid.UUID
}

// UpdateOAuthServiceParams is parameters of update_oauth_service operation.
type UpdateOAuthServiceParams struct {
	ServiceID uuid.UUID
}
