// Code generated by ogen, DO NOT EDIT.
package api

type BulkInviteEnvironmentUsersRes interface {
	bulkInviteEnvironmentUsersRes()
}

type CreateChatRes interface {
	createChatRes()
}

type CreateChatTitleRes interface {
	createChatTitleRes()
}

type CreateEntityDefinitionRes interface {
	createEntityDefinitionRes()
}

type CreateEntityRelationRes interface {
	createEntityRelationRes()
}

type CreateEntityRes interface {
	createEntityRes()
}

type CreateEnvironmentRes interface {
	createEnvironmentRes()
}

type CreateEnvironmentUserRes interface {
	createEnvironmentUserRes()
}

type CreateMcpendpointRes interface {
	createMcpendpointRes()
}

type CreateModelRes interface {
	createModelRes()
}

type CreateModelproviderRes interface {
	createModelproviderRes()
}

type CreateOAuthServiceRes interface {
	createOAuthServiceRes()
}

type CreateTokenRes interface {
	createTokenRes()
}

type DeleteChatRes interface {
	deleteChatRes()
}

type DeleteEntityDefinitionRes interface {
	deleteEntityDefinitionRes()
}

type DeleteEntityRelationRes interface {
	deleteEntityRelationRes()
}

type DeleteEntityRes interface {
	deleteEntityRes()
}

type DeleteEnvironmentUserRes interface {
	deleteEnvironmentUserRes()
}

type DeleteMcpendpointRes interface {
	deleteMcpendpointRes()
}

type DeleteModelRes interface {
	deleteModelRes()
}

type DeleteModelproviderRes interface {
	deleteModelproviderRes()
}

type DeleteOAuthServiceRes interface {
	deleteOAuthServiceRes()
}

type ExchangeOAuthTokenRes interface {
	exchangeOAuthTokenRes()
}

type GetChatMessagesRes interface {
	getChatMessagesRes()
}

type GetChatRes interface {
	getChatRes()
}

type GetChatsRes interface {
	getChatsRes()
}

type GetEntitiesRes interface {
	getEntitiesRes()
}

type GetEntityDefinitionsRes interface {
	getEntityDefinitionsRes()
}

type GetEntityRes interface {
	getEntityRes()
}

type GetEnvironmentStatusRes interface {
	getEnvironmentStatusRes()
}

type GetEnvironmentUserRes interface {
	getEnvironmentUserRes()
}

type GetEnvironmentsRes interface {
	getEnvironmentsRes()
}

type GetMcpendpointRes interface {
	getMcpendpointRes()
}

type GetMcpendpointsRes interface {
	getMcpendpointsRes()
}

type GetModelRes interface {
	getModelRes()
}

type GetModelproviderRes interface {
	getModelproviderRes()
}

type GetModelprovidersRes interface {
	getModelprovidersRes()
}

type GetModelsRes interface {
	getModelsRes()
}

type GetOAuthAuthorizationURLRes interface {
	getOAuthAuthorizationURLRes()
}

type GetOAuthServiceRes interface {
	getOAuthServiceRes()
}

type GetPendingInvitationsRes interface {
	getPendingInvitationsRes()
}

type GetSubscriptionsRes interface {
	getSubscriptionsRes()
}

type GetTokensRes interface {
	getTokensRes()
}

type InviteEnvironmentUserRes interface {
	inviteEnvironmentUserRes()
}

type ListEnvironmentUsersRes interface {
	listEnvironmentUsersRes()
}

type ListOAuthServicesRes interface {
	listOAuthServicesRes()
}

type ListOAuthTokensRes interface {
	listOAuthTokensRes()
}

type PostChatMessagesRes interface {
	postChatMessagesRes()
}

type PostClerkWebhookRes interface {
	postClerkWebhookRes()
}

type PostStripeWebhookRes interface {
	postStripeWebhookRes()
}

type RevokeOAuthTokenRes interface {
	revokeOAuthTokenRes()
}

type UpdateChatRes interface {
	updateChatRes()
}

type UpdateEnvironmentUserRes interface {
	updateEnvironmentUserRes()
}

type UpdateMcpendpointRes interface {
	updateMcpendpointRes()
}

type UpdateOAuthServiceRes interface {
	updateOAuthServiceRes()
}
