// Code generated by ogen, DO NOT EDIT.

package v1

// setDefaults set default value of fields.
func (s *AnthropicModelProviderCreate) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AnthropicModelProviderResponse) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ApiTokenResponse) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BulkEntityRelationCreateRequest) setDefaults() {
	{
		val := string("default")
		s.Namespace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BulkEntityRelationResponse) setDefaults() {
	{
		val := string("default")
		s.Namespace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatSession) setDefaults() {
	{
		val := ChatVisibility("private")
		s.Visibility.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatSessionCreate) setDefaults() {
	{
		val := ChatVisibility("private")
		s.Visibility.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatSessionUpdate) setDefaults() {
	{
		val := ChatVisibility("private")
		s.Visibility.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatSuggestionCreate) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatSuggestionResponse) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.IsSystem.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConfiguredProviderCreate) setDefaults() {
	{
		val := bool(true)
		s.Enabled.SetTo(val)
	}
	{
		val := int(300)
		s.Interval.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityDefinitionResponse) setDefaults() {
	{
		val := string("v1")
		s.Name.SetTo(val)
	}
	{
		val := bool(true)
		s.Storage.SetTo(val)
	}
	{
		val := bool(true)
		s.Served.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityDefinitionSpec) setDefaults() {
	{
		val := string("v1")
		s.Name.SetTo(val)
	}
	{
		val := bool(true)
		s.Storage.SetTo(val)
	}
	{
		val := bool(true)
		s.Served.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityReference) setDefaults() {
	{
		val := string("default")
		s.Namespace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityReferenceResponse) setDefaults() {
	{
		val := string("default")
		s.Namespace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityRelation) setDefaults() {
	{
		val := string("default")
		s.Namespace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityRelationResponse) setDefaults() {
	{
		val := string("default")
		s.Namespace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityStatus) setDefaults() {
	{
		val := bool(false)
		s.IsOrphan.SetTo(val)
	}
	{
		val := int(1)
		s.Generation.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EnvironmentResponse) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EnvironmentUserCreate) setDefaults() {
	{
		val := EnvironmentUserCreateRole("member")
		s.Role.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EnvironmentUserInvite) setDefaults() {
	{
		val := EnvironmentUserInviteRole("member")
		s.Role.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MCPEndpointCreate) setDefaults() {
	{
		val := bool(false)
		s.DevgraphAuth.SetTo(val)
	}
	{
		val := bool(false)
		s.SupportsResources.SetTo(val)
	}
	{
		val := bool(false)
		s.Immutable.SetTo(val)
	}
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.AllowRenderers.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MCPEndpointResponse) setDefaults() {
	{
		val := bool(false)
		s.DevgraphAuth.SetTo(val)
	}
	{
		val := bool(false)
		s.SupportsResources.SetTo(val)
	}
	{
		val := bool(false)
		s.Immutable.SetTo(val)
	}
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.AllowRenderers.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MCPToolsResponse) setDefaults() {
	{
		val := float64(0)
		s.LoadTime.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelCreate) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelResponse) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MoleculeData) setDefaults() {
	{
		val := bool(false)
		s.RequiresAuth.SetTo(val)
	}
	{
		val := bool(false)
		s.Deprecated.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OAuthServiceCreate) setDefaults() {
	{
		val := bool(true)
		s.IsActive.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OpenAIModelProviderCreate) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OpenAIModelProviderResponse) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptCreate) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDefault.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptResponse) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.IsDefault.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *XAIModelProviderCreate) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *XAIModelProviderResponse) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}
