// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/google/uuid"
)

// BulkInviteEnvironmentUsersParams is parameters of bulk_invite_environment_users operation.
type BulkInviteEnvironmentUsersParams struct {
	EnvironmentID uuid.UUID
}

// CleanupOrphanedEntitiesParams is parameters of cleanup_orphaned_entities operation.
type CleanupOrphanedEntitiesParams struct {
	// Namespace to clean up (default: 'default').
	Namespace OptString `json:",omitempty,omitzero"`
	// Only delete orphans older than this many hours.
	MaxAgeHours OptInt `json:",omitempty,omitzero"`
}

// CreateEntityParams is parameters of create_entity operation.
type CreateEntityParams struct {
	Group     string
	Version   string
	Namespace string
	Plural    string
}

// CreateEntityRelationParams is parameters of create_entity_relation operation.
type CreateEntityRelationParams struct {
	Namespace string
}

// CreateEnvironmentUserParams is parameters of create_environment_user operation.
type CreateEnvironmentUserParams struct {
	EnvironmentID uuid.UUID
}

// DeleteChatParams is parameters of delete_chat operation.
type DeleteChatParams struct {
	ChatID string
}

// DeleteChatsBulkParams is parameters of delete_chats_bulk operation.
type DeleteChatsBulkParams struct {
	// List of chat IDs to delete.
	ChatIds []string `json:",omitempty"`
}

// DeleteEntityParams is parameters of delete_entity operation.
type DeleteEntityParams struct {
	Group     string
	Version   string
	Kind      string
	Namespace string
	Name      string
}

// DeleteEntityDefinitionParams is parameters of delete_entity_definition operation.
type DeleteEntityDefinitionParams struct {
	DefinitionID uuid.UUID
	// If true, mark entities as orphans instead of deleting them immediately.
	MarkOrphansOnly OptBool `json:",omitempty,omitzero"`
}

// DeleteEntityRelationParams is parameters of delete_entity_relation operation.
type DeleteEntityRelationParams struct {
	Namespace string
}

// DeleteEnvironmentUserParams is parameters of delete_environment_user operation.
type DeleteEnvironmentUserParams struct {
	EnvironmentID uuid.UUID
	UserID        string
}

// DeleteMcpToolAssociationParams is parameters of delete_mcp_tool_association operation.
type DeleteMcpToolAssociationParams struct {
	AssociationID uuid.UUID
}

// DeleteMcpendpointParams is parameters of delete_mcpendpoint operation.
type DeleteMcpendpointParams struct {
	McpendpointID uuid.UUID
}

// DeleteModelParams is parameters of delete_model operation.
type DeleteModelParams struct {
	ModelName string
}

// DeleteModelproviderParams is parameters of delete_modelprovider operation.
type DeleteModelproviderParams struct {
	ProviderID uuid.UUID
}

// DeleteOAuthServiceParams is parameters of delete_oauth_service operation.
type DeleteOAuthServiceParams struct {
	ServiceID uuid.UUID
}

// DeletePromptParams is parameters of delete_prompt operation.
type DeletePromptParams struct {
	PromptID uuid.UUID
}

// DeleteTokenParams is parameters of delete_token operation.
type DeleteTokenParams struct {
	TokenID uuid.UUID
}

// GetChatParams is parameters of get_chat operation.
type GetChatParams struct {
	ChatID string
}

// GetChatMessagesParams is parameters of get_chat_messages operation.
type GetChatMessagesParams struct {
	ChatID string
	Limit  OptInt `json:",omitempty,omitzero"`
	Offset OptInt `json:",omitempty,omitzero"`
}

// GetChatsParams is parameters of get_chats operation.
type GetChatsParams struct {
	Offset OptInt `json:",omitempty,omitzero"`
	Limit  OptInt `json:",omitempty,omitzero"`
}

// GetEntitiesParams is parameters of get_entities operation.
type GetEntitiesParams struct {
	Name   OptString `json:",omitempty,omitzero"`
	Label  OptString `json:",omitempty,omitzero"`
	Limit  OptInt    `json:",omitempty,omitzero"`
	Offset OptInt    `json:",omitempty,omitzero"`
	// Comma-separated field selectors in format 'key=value', supports dot notation for nested properties.
	FieldSelector OptString `json:",omitempty,omitzero"`
}

// GetEntityParams is parameters of get_entity operation.
type GetEntityParams struct {
	Group     string
	Version   string
	Kind      string
	Namespace string
	Name      string
}

// GetEntityByUIDParams is parameters of get_entity_by_uid operation.
type GetEntityByUIDParams struct {
	UID       string
	Namespace OptString `json:",omitempty,omitzero"`
}

// GetEntityToolsParams is parameters of get_entity_tools operation.
type GetEntityToolsParams struct {
	EntityDefinitionID uuid.UUID
	EntityVersionID    OptNilUUID `json:",omitempty,omitzero"`
}

// GetEnvironmentStatusParams is parameters of get_environment_status operation.
type GetEnvironmentStatusParams struct {
	EnvID uuid.UUID
}

// GetEnvironmentUserParams is parameters of get_environment_user operation.
type GetEnvironmentUserParams struct {
	EnvironmentID uuid.UUID
	UserID        string
}

// GetMcpEndpointEntityTypesParams is parameters of get_mcp_endpoint_entity_types operation.
type GetMcpEndpointEntityTypesParams struct {
	McpendpointName string
	ToolName        OptNilString `json:",omitempty,omitzero"`
}

// GetMcpendpointParams is parameters of get_mcpendpoint operation.
type GetMcpendpointParams struct {
	McpendpointID uuid.UUID
}

// GetModelParams is parameters of get_model operation.
type GetModelParams struct {
	ModelName string
}

// GetModelproviderParams is parameters of get_modelprovider operation.
type GetModelproviderParams struct {
	ProviderID uuid.UUID
}

// GetOAuthServiceParams is parameters of get_oauth_service operation.
type GetOAuthServiceParams struct {
	ServiceID uuid.UUID
}

// GetPendingInvitationsParams is parameters of get_pending_invitations operation.
type GetPendingInvitationsParams struct {
	EnvironmentID uuid.UUID
}

// GetPromptParams is parameters of get_prompt operation.
type GetPromptParams struct {
	PromptID uuid.UUID
}

// InviteEnvironmentUserParams is parameters of invite_environment_user operation.
type InviteEnvironmentUserParams struct {
	EnvironmentID uuid.UUID
}

// ListEnvironmentUsersParams is parameters of list_environment_users operation.
type ListEnvironmentUsersParams struct {
	EnvironmentID uuid.UUID
}

// ListMcpendpointToolsParams is parameters of list_mcpendpoint_tools operation.
type ListMcpendpointToolsParams struct {
	McpendpointID uuid.UUID
}

// ListOAuthServicesParams is parameters of list_oauth_services operation.
type ListOAuthServicesParams struct {
	// Only return active services.
	ActiveOnly OptBool `json:",omitempty,omitzero"`
}

// ListOrphanedEntitiesParams is parameters of list_orphaned_entities operation.
type ListOrphanedEntitiesParams struct {
	// Namespace to query (default: 'default').
	Namespace OptString `json:",omitempty,omitzero"`
}

// ListPromptsParams is parameters of list_prompts operation.
type ListPromptsParams struct {
	Active OptNullBooleanEnum `json:",omitempty,omitzero"`
}

// PostChatMessagesParams is parameters of post_chat_messages operation.
type PostChatMessagesParams struct {
	ChatID string
}

// PostClerkWebhookParams is parameters of post_clerk_webhook operation.
type PostClerkWebhookParams struct {
	SvixID        string
	SvixTimestamp string
	SvixSignature string
}

// PostStripeWebhookParams is parameters of post_stripe_webhook operation.
type PostStripeWebhookParams struct {
	StripeSignature string
}

// RevokeOAuthTokenParams is parameters of revoke_oauth_token operation.
type RevokeOAuthTokenParams struct {
	ServiceName string
}

// UpdateChatParams is parameters of update_chat operation.
type UpdateChatParams struct {
	ChatID string
}

// UpdateEnvironmentUserParams is parameters of update_environment_user operation.
type UpdateEnvironmentUserParams struct {
	EnvironmentID uuid.UUID
	UserID        string
}

// UpdateMcpendpointParams is parameters of update_mcpendpoint operation.
type UpdateMcpendpointParams struct {
	McpendpointID uuid.UUID
}

// UpdateModelParams is parameters of update_model operation.
type UpdateModelParams struct {
	ModelName string
}

// UpdateModelproviderParams is parameters of update_modelprovider operation.
type UpdateModelproviderParams struct {
	ProviderID uuid.UUID
}

// UpdateOAuthServiceParams is parameters of update_oauth_service operation.
type UpdateOAuthServiceParams struct {
	ServiceID uuid.UUID
}

// UpdatePromptParams is parameters of update_prompt operation.
type UpdatePromptParams struct {
	PromptID uuid.UUID
}

// UpdateTokenParams is parameters of update_token operation.
type UpdateTokenParams struct {
	TokenID uuid.UUID
}
