// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// BulkInviteEnvironmentUsers implements bulk_invite_environment_users operation.
	//
	// Bulk invite multiple users to an environment (organization).
	//
	// POST /api/v1/environments/{environment_id}/users/bulk-invite
	BulkInviteEnvironmentUsers(ctx context.Context, req *EnvironmentUserBulkInvite, params BulkInviteEnvironmentUsersParams) (BulkInviteEnvironmentUsersRes, error)
	// CheckEntitlement implements check_entitlement operation.
	//
	// Check a specific entitlement for the authenticated user.
	// For numeric limits (e.g., max_environments), returns current usage and remaining quota.
	// For boolean features (e.g., enable_sso), returns whether the feature is enabled.
	//
	// GET /api/v1/entitlements/check/{entitlement_type}
	CheckEntitlement(ctx context.Context, params CheckEntitlementParams) (CheckEntitlementRes, error)
	// CleanupOrphanedEntities implements cleanup_orphaned_entities operation.
	//
	// Delete all entities marked as orphans. Requires 'delete:entities' permission.
	//
	// DELETE /api/v1/entities/orphans
	CleanupOrphanedEntities(ctx context.Context, params CleanupOrphanedEntitiesParams) (CleanupOrphanedEntitiesRes, error)
	// CreateChat implements create_chat operation.
	//
	// Create Chat.
	//
	// POST /api/v1/chats/
	CreateChat(ctx context.Context, req *ChatSessionCreate) (CreateChatRes, error)
	// CreateChatSuggestion implements create_chat_suggestion operation.
	//
	// Create a new chat suggestion for the environment.
	//
	// POST /api/v1/chats/suggestions
	CreateChatSuggestion(ctx context.Context, req *ChatSuggestionCreate) (CreateChatSuggestionRes, error)
	// CreateChatTitle implements create_chat_title operation.
	//
	// Generate a title for a chat based on the first message.
	//
	// POST /api/v1/chats/title
	CreateChatTitle(ctx context.Context, req *ChatTitleRequest) (CreateChatTitleRes, error)
	// CreateConfiguredProvider implements create_configured_provider operation.
	//
	// Create a new configured discovery provider.
	// The provider configuration (including secrets) will be encrypted and stored.
	//
	// POST /api/v1/discovery/configured-providers
	CreateConfiguredProvider(ctx context.Context, req *ConfiguredProviderCreate) (CreateConfiguredProviderRes, error)
	// CreateEntitiesBulk implements create_entities_bulk operation.
	//
	// Creates multiple entities in a single request with concurrent processing. Provides detailed
	// success/failure information for each entity. Requires 'create:entities' permission.
	//
	// POST /api/v1/entities/bulk
	CreateEntitiesBulk(ctx context.Context, req []Entity, params CreateEntitiesBulkParams) (CreateEntitiesBulkRes, error)
	// CreateEntity implements create_entity operation.
	//
	// Creates a new entity based on the specified group, version, namespace, and kind. Requires
	// 'create:entities' permission.
	//
	// POST /api/v1/entities/{group}/{version}/namespace/{namespace}/{plural}
	CreateEntity(ctx context.Context, req *Entity, params CreateEntityParams) (CreateEntityRes, error)
	// CreateEntityDefinition implements create_entity_definition operation.
	//
	// Create a new entity definition with schema and storage configuration.
	//
	// POST /api/v1/entities/definitions
	CreateEntityDefinition(ctx context.Context, req *EntityDefinitionSpec) (CreateEntityDefinitionRes, error)
	// CreateEntityRelation implements create_entity_relation operation.
	//
	// Create Entity Relation.
	//
	// POST /api/v1/entities/relations
	CreateEntityRelation(ctx context.Context, req *EntityRelation, params CreateEntityRelationParams) (CreateEntityRelationRes, error)
	// CreateEntityRelationsBulk implements create_entity_relations_bulk operation.
	//
	// Creates multiple entity relations in a single request. Provides detailed success/failure
	// information for each relation. Requires 'create:entityrelations' permission.
	//
	// POST /api/v1/entities/relations/bulk
	CreateEntityRelationsBulk(ctx context.Context, req *BulkEntityRelationCreateRequest) (CreateEntityRelationsBulkRes, error)
	// CreateEnvironment implements create_environment operation.
	//
	// Create Environment.
	//
	// POST /api/v1/environments
	CreateEnvironment(ctx context.Context, req *EnvironmentCreate) (CreateEnvironmentRes, error)
	// CreateEnvironmentUser implements create_environment_user operation.
	//
	// Create a new environment user by adding them to the Clerk organization.
	//
	// POST /api/v1/environments/{environment_id}/users
	CreateEnvironmentUser(ctx context.Context, req *EnvironmentUserCreate, params CreateEnvironmentUserParams) (CreateEnvironmentUserRes, error)
	// CreateMcpToolAssociation implements create_mcp_tool_association operation.
	//
	// Create an association between an MCP tool and an entity definition.
	//
	// POST /api/v1/mcp/tool-associations
	CreateMcpToolAssociation(ctx context.Context, req *MCPToolEntityAssociationCreate) (CreateMcpToolAssociationRes, error)
	// CreateMcpendpoint implements create_mcpendpoint operation.
	//
	// Create a new MCP Endpoint configuration.
	//
	// POST /api/v1/mcp/endpoints
	CreateMcpendpoint(ctx context.Context, req *MCPEndpointCreate) (CreateMcpendpointRes, error)
	// CreateModel implements create_model operation.
	//
	// Create a new AI model configuration with provider details in the environment.
	//
	// POST /api/v1/models
	CreateModel(ctx context.Context, req *ModelCreate) (CreateModelRes, error)
	// CreateModelprovider implements create_modelprovider operation.
	//
	// Create a new Model Provider configuration.
	//
	// POST /api/v1/models/providers
	CreateModelprovider(ctx context.Context, req *ModelProviderCreate) (CreateModelproviderRes, error)
	// CreateOAuthService implements create_oauth_service operation.
	//
	// Create Oauth Service.
	//
	// POST /api/v1/oauth/services
	CreateOAuthService(ctx context.Context, req *OAuthServiceCreate) (CreateOAuthServiceRes, error)
	// CreatePrompt implements create_prompt operation.
	//
	// Create a new prompt for the environment.
	//
	// POST /api/v1/prompts
	CreatePrompt(ctx context.Context, req *PromptCreate) (CreatePromptRes, error)
	// CreateToken implements create_token operation.
	//
	// Create Token.
	//
	// POST /api/v1/tokens
	CreateToken(ctx context.Context, req *ApiTokenCreate) (CreateTokenRes, error)
	// DeleteChat implements delete_chat operation.
	//
	// Delete Chat.
	//
	// DELETE /api/v1/chats/{chat_id}
	DeleteChat(ctx context.Context, params DeleteChatParams) (DeleteChatRes, error)
	// DeleteChatSuggestion implements delete_chat_suggestion operation.
	//
	// Delete a chat suggestion. Can only delete user's own suggestions (not system ones).
	//
	// DELETE /api/v1/chats/suggestions/{suggestion_id}
	DeleteChatSuggestion(ctx context.Context, params DeleteChatSuggestionParams) (DeleteChatSuggestionRes, error)
	// DeleteChatsBulk implements delete_chats_bulk operation.
	//
	// Bulk delete multiple chat sessions.
	//
	// DELETE /api/v1/chats/
	DeleteChatsBulk(ctx context.Context, req *BulkDeleteRequest) (DeleteChatsBulkRes, error)
	// DeleteConfiguredProvider implements delete_configured_provider operation.
	//
	// Delete a configured discovery provider.
	//
	// DELETE /api/v1/discovery/configured-providers/{provider_id}
	DeleteConfiguredProvider(ctx context.Context, params DeleteConfiguredProviderParams) (DeleteConfiguredProviderRes, error)
	// DeleteEntity implements delete_entity operation.
	//
	// Deletes a specific entity from the ontology. Requires 'delete:entities' permission.
	//
	// DELETE /api/v1/entities/{group}/{version}/{kind}/{namespace}/{name}
	DeleteEntity(ctx context.Context, params DeleteEntityParams) (DeleteEntityRes, error)
	// DeleteEntityDefinition implements delete_entity_definition operation.
	//
	// Deletes an entity definition and all its versions. Requires 'delete:entitydefinitions' permission.
	//
	// DELETE /api/v1/entities/definitions/{definition_id}
	DeleteEntityDefinition(ctx context.Context, params DeleteEntityDefinitionParams) (DeleteEntityDefinitionRes, error)
	// DeleteEntityRelation implements delete_entity_relation operation.
	//
	// Deletes a specific relation between two entities. Requires 'delete:entityrelations' permission.
	//
	// DELETE /api/v1/entities/relations
	DeleteEntityRelation(ctx context.Context, req *EntityRelation, params DeleteEntityRelationParams) (DeleteEntityRelationRes, error)
	// DeleteEnvironment implements delete_environment operation.
	//
	// Soft delete an environment.
	// This marks the environment as deleted (sets deleted_at timestamp) which triggers
	// the Kubernetes controller to clean up all associated resources (namespace, database, etc.).
	// The environment record is retained for the configured retention period for potential recovery.
	// For permanent GDPR-compliant deletion, use the Admin API endpoint.
	//
	// DELETE /api/v1/environments/{env_id}
	DeleteEnvironment(ctx context.Context, params DeleteEnvironmentParams) (DeleteEnvironmentRes, error)
	// DeleteEnvironmentInvitation implements delete_environment_invitation operation.
	//
	// Revoke a pending invitation to an environment (organization).
	//
	// DELETE /api/v1/environments/{environment_id}/users/invitations/{invitation_id}
	DeleteEnvironmentInvitation(ctx context.Context, params DeleteEnvironmentInvitationParams) (DeleteEnvironmentInvitationRes, error)
	// DeleteEnvironmentUser implements delete_environment_user operation.
	//
	// Remove a user from an environment (organization).
	//
	// DELETE /api/v1/environments/{environment_id}/users/{user_id}
	DeleteEnvironmentUser(ctx context.Context, params DeleteEnvironmentUserParams) (DeleteEnvironmentUserRes, error)
	// DeleteMcpToolAssociation implements delete_mcp_tool_association operation.
	//
	// Delete an MCP tool-entity association.
	//
	// DELETE /api/v1/mcp/tool-associations/{association_id}
	DeleteMcpToolAssociation(ctx context.Context, params DeleteMcpToolAssociationParams) (DeleteMcpToolAssociationRes, error)
	// DeleteMcpendpoint implements delete_mcpendpoint operation.
	//
	// Delete a specific MCP Endpoint configuration by ID.
	//
	// DELETE /api/v1/mcp/endpoints/{mcpendpoint_id}
	DeleteMcpendpoint(ctx context.Context, params DeleteMcpendpointParams) (DeleteMcpendpointRes, error)
	// DeleteModel implements delete_model operation.
	//
	// Soft delete an AI model configuration by name.
	//
	// DELETE /api/v1/models/{model_name}
	DeleteModel(ctx context.Context, params DeleteModelParams) (DeleteModelRes, error)
	// DeleteModelprovider implements delete_modelprovider operation.
	//
	// Delete a specific Model Provider configuration by ID.
	//
	// DELETE /api/v1/models/providers/{provider_id}
	DeleteModelprovider(ctx context.Context, params DeleteModelproviderParams) (DeleteModelproviderRes, error)
	// DeleteOAuthService implements delete_oauth_service operation.
	//
	// Delete Oauth Service.
	//
	// DELETE /api/v1/oauth/services/{service_id}
	DeleteOAuthService(ctx context.Context, params DeleteOAuthServiceParams) (DeleteOAuthServiceRes, error)
	// DeletePrompt implements delete_prompt operation.
	//
	// Delete a specific prompt by ID.
	//
	// DELETE /api/v1/prompts/{prompt_id}
	DeletePrompt(ctx context.Context, params DeletePromptParams) (DeletePromptRes, error)
	// DeleteToken implements delete_token operation.
	//
	// Delete a specific API token by ID.
	//
	// DELETE /api/v1/tokens/{token_id}
	DeleteToken(ctx context.Context, params DeleteTokenParams) (DeleteTokenRes, error)
	// ExchangeOAuthToken implements exchange_oauth_token operation.
	//
	// Exchange Code For Token.
	//
	// POST /api/v1/oauth/token
	ExchangeOAuthToken(ctx context.Context, req *OAuthTokenExchange) (ExchangeOAuthTokenRes, error)
	// GetAllProviderVersions implements get_all_provider_versions operation.
	//
	// Get version support info for all available provider types.
	//
	// GET /api/v1/discovery/versions
	GetAllProviderVersions(ctx context.Context) (GetAllProviderVersionsRes, error)
	// GetChat implements get_chat operation.
	//
	// Get Chat.
	//
	// GET /api/v1/chats/{chat_id}
	GetChat(ctx context.Context, params GetChatParams) (GetChatRes, error)
	// GetChatMessages implements get_chat_messages operation.
	//
	// Get Chat Messages.
	//
	// GET /api/v1/chats/{chat_id}/messages
	GetChatMessages(ctx context.Context, params GetChatMessagesParams) (GetChatMessagesRes, error)
	// GetChats implements get_chats operation.
	//
	// Get Chats.
	//
	// GET /api/v1/chats/
	GetChats(ctx context.Context, params GetChatsParams) (GetChatsRes, error)
	// GetConfiguredProvider implements get_configured_provider operation.
	//
	// Get a specific configured discovery provider.
	// Secrets in the provider configuration are masked.
	//
	// GET /api/v1/discovery/configured-providers/{provider_id}
	GetConfiguredProvider(ctx context.Context, params GetConfiguredProviderParams) (GetConfiguredProviderRes, error)
	// GetDeprecatedProviderConfigs implements get_deprecated_provider_configs operation.
	//
	// Get all provider instances using deprecated config versions.
	//
	// GET /api/v1/discovery/versions/deprecated
	GetDeprecatedProviderConfigs(ctx context.Context, params GetDeprecatedProviderConfigsParams) (GetDeprecatedProviderConfigsRes, error)
	// GetDiscoveryProviderConfigSchema implements get_discovery_provider_config_schema operation.
	//
	// Get the configuration schema for a specific discovery provider type.
	// Args:
	// provider_type: The type identifier of the provider (e.g., 'github', 'gitlab')
	// Returns:
	// JSON schema for the provider's configuration.
	//
	// GET /api/v1/discovery/providers/{provider_type}/config-schema
	GetDiscoveryProviderConfigSchema(ctx context.Context, params GetDiscoveryProviderConfigSchemaParams) (GetDiscoveryProviderConfigSchemaRes, error)
	// GetEntities implements get_entities operation.
	//
	// Retrieves entities from the ontology, optionally filtered by field selectors. Field selectors use
	// dot notation for nested properties (e.g., 'spec.metadata.owner=team-a'). Requires 'read:entities'
	// permission.
	//
	// GET /api/v1/entities/
	GetEntities(ctx context.Context, params GetEntitiesParams) (GetEntitiesRes, error)
	// GetEntitlements implements get_entitlements operation.
	//
	// Get all entitlements and current usage for the authenticated user.
	//
	// GET /api/v1/entitlements
	GetEntitlements(ctx context.Context) (GetEntitlementsRes, error)
	// GetEntity implements get_entity operation.
	//
	// Fetches a specific entity based on group, version, namespace, plural, and name, including related
	// entities and relations. Requires 'read:entities' permission.
	//
	// GET /api/v1/entities/{group}/{version}/{kind}/{namespace}/{name}
	GetEntity(ctx context.Context, params GetEntityParams) (GetEntityRes, error)
	// GetEntityByUID implements get_entity_by_uid operation.
	//
	// Fetches a specific entity by its unique identifier (UID), including related entities and relations.
	//  Requires 'read:entities' permission.
	//
	// GET /api/v1/entities/uid/{uid}
	GetEntityByUID(ctx context.Context, params GetEntityByUIDParams) (GetEntityByUIDRes, error)
	// GetEntityDefinitions implements get_entity_definitions operation.
	//
	// Fetches a list of all entity definitions and their associated versions from the database. Requires
	// 'list:entitydefinitions' permission.
	//
	// GET /api/v1/entities/definitions
	GetEntityDefinitions(ctx context.Context) (GetEntityDefinitionsRes, error)
	// GetEntityTools implements get_entity_tools operation.
	//
	// Get all MCP tools associated with an entity definition.
	//
	// GET /api/v1/mcp/entity-definitions/{entity_definition_id}/tools
	GetEntityTools(ctx context.Context, params GetEntityToolsParams) (GetEntityToolsRes, error)
	// GetEnvironmentStatus implements get_environment_status operation.
	//
	// Get Environment Status.
	//
	// GET /api/v1/environments/{env_id}/status
	GetEnvironmentStatus(ctx context.Context, params GetEnvironmentStatusParams) (GetEnvironmentStatusRes, error)
	// GetEnvironmentUser implements get_environment_user operation.
	//
	// Get a specific environment user.
	//
	// GET /api/v1/environments/{environment_id}/users/{user_id}
	GetEnvironmentUser(ctx context.Context, params GetEnvironmentUserParams) (GetEnvironmentUserRes, error)
	// GetEnvironments implements get_environments operation.
	//
	// Get Environments.
	//
	// GET /api/v1/environments
	GetEnvironments(ctx context.Context) (GetEnvironmentsRes, error)
	// GetMcpEndpointEntityTypes implements get_mcp_endpoint_entity_types operation.
	//
	// Get all entity types associated with an MCP endpoint's tools.
	//
	// GET /api/v1/mcp/endpoints/{mcpendpoint_name}/entity-types
	GetMcpEndpointEntityTypes(ctx context.Context, params GetMcpEndpointEntityTypesParams) (GetMcpEndpointEntityTypesRes, error)
	// GetMcpendpoint implements get_mcpendpoint operation.
	//
	// Get a specific MCP Endpoint configuration by ID.
	//
	// GET /api/v1/mcp/endpoints/{mcpendpoint_id}
	GetMcpendpoint(ctx context.Context, params GetMcpendpointParams) (GetMcpendpointRes, error)
	// GetMcpendpoints implements get_mcpendpoints operation.
	//
	// List all MCP Endpoint configurations for the authenticated user and environment.
	//
	// GET /api/v1/mcp/endpoints
	GetMcpendpoints(ctx context.Context) (GetMcpendpointsRes, error)
	// GetModel implements get_model operation.
	//
	// Retrieve a specific AI model configuration by name.
	//
	// GET /api/v1/models/{model_name}
	GetModel(ctx context.Context, params GetModelParams) (GetModelRes, error)
	// GetModelprovider implements get_modelprovider operation.
	//
	// Get a specific Model Provider configuration by ID.
	//
	// GET /api/v1/models/providers/{provider_id}
	GetModelprovider(ctx context.Context, params GetModelproviderParams) (GetModelproviderRes, error)
	// GetModelproviders implements get_modelproviders operation.
	//
	// List all Model Provider configurations for the authenticated user and environment.
	//
	// GET /api/v1/models/providers
	GetModelproviders(ctx context.Context) (GetModelprovidersRes, error)
	// GetModels implements get_models operation.
	//
	// Retrieve all AI model configurations for the current environment.
	//
	// GET /api/v1/models
	GetModels(ctx context.Context) (GetModelsRes, error)
	// GetOAuthAuthorizationURL implements get_oauth_authorization_url operation.
	//
	// Get Authorization Url.
	//
	// POST /api/v1/oauth/authorize
	GetOAuthAuthorizationURL(ctx context.Context, req *OAuthAuthorizationRequest) (GetOAuthAuthorizationURLRes, error)
	// GetOAuthService implements get_oauth_service operation.
	//
	// Get Oauth Service.
	//
	// GET /api/v1/oauth/services/{service_id}
	GetOAuthService(ctx context.Context, params GetOAuthServiceParams) (GetOAuthServiceRes, error)
	// GetPendingInvitations implements get_pending_invitations operation.
	//
	// Get all pending invitations for an environment (users who have been invited but haven't joined
	// yet).
	//
	// GET /api/v1/environments/{environment_id}/users/pending
	GetPendingInvitations(ctx context.Context, params GetPendingInvitationsParams) (GetPendingInvitationsRes, error)
	// GetPrompt implements get_prompt operation.
	//
	// Get a specific prompt by ID.
	//
	// GET /api/v1/prompts/{prompt_id}
	GetPrompt(ctx context.Context, params GetPromptParams) (GetPromptRes, error)
	// GetSubscriptions implements get_subscriptions operation.
	//
	// Get Subscriptions.
	//
	// GET /api/v1/subscriptions
	GetSubscriptions(ctx context.Context) (GetSubscriptionsRes, error)
	// GetSystemDefaultPrompt implements get_system_default_prompt operation.
	//
	// Get the built-in system default prompt.
	//
	// GET /api/v1/prompts/system-default
	GetSystemDefaultPrompt(ctx context.Context) (GetSystemDefaultPromptRes, error)
	// GetTokens implements get_tokens operation.
	//
	// Get all API tokens for the authenticated user.
	//
	// GET /api/v1/tokens
	GetTokens(ctx context.Context) (GetTokensRes, error)
	// InviteEnvironmentUser implements invite_environment_user operation.
	//
	// Invite a user to an environment (organization).
	//
	// POST /api/v1/environments/{environment_id}/users/invite
	InviteEnvironmentUser(ctx context.Context, req *EnvironmentUserInvite, params InviteEnvironmentUserParams) (InviteEnvironmentUserRes, error)
	// ListChatSuggestions implements list_chat_suggestions operation.
	//
	// List chat suggestions. Returns system-wide suggestions + environment/user-specific ones.
	//
	// GET /api/v1/chats/suggestions
	ListChatSuggestions(ctx context.Context, params ListChatSuggestionsParams) (ListChatSuggestionsRes, error)
	// ListConfiguredProviders implements list_configured_providers operation.
	//
	// List all configured discovery providers for the current environment.
	// Secrets in provider configurations are masked.
	//
	// GET /api/v1/discovery/configured-providers
	ListConfiguredProviders(ctx context.Context) (ListConfiguredProvidersRes, error)
	// ListDiscoveryProviders implements list_discovery_providers operation.
	//
	// List all available discovery provider types with their configuration schemas.
	// This endpoint discovers all registered discovery providers using the plugin system
	// and returns their metadata including JSON schemas for configuration.
	//
	// GET /api/v1/discovery/providers
	ListDiscoveryProviders(ctx context.Context) (ListDiscoveryProvidersRes, error)
	// ListEnvironmentUsers implements list_environment_users operation.
	//
	// List all users in an environment (organization members).
	//
	// GET /api/v1/environments/{environment_id}/users
	ListEnvironmentUsers(ctx context.Context, params ListEnvironmentUsersParams) (ListEnvironmentUsersRes, error)
	// ListMcpendpointTools implements list_mcpendpoint_tools operation.
	//
	// List all available tools from a specific MCP Endpoint.
	// This interrogates the MCP server to discover its available tools.
	//
	// GET /api/v1/mcp/endpoints/{mcpendpoint_id}/tools
	ListMcpendpointTools(ctx context.Context, params ListMcpendpointToolsParams) (ListMcpendpointToolsRes, error)
	// ListOAuthServices implements list_oauth_services operation.
	//
	// List Oauth Services.
	//
	// GET /api/v1/oauth/services
	ListOAuthServices(ctx context.Context, params ListOAuthServicesParams) (ListOAuthServicesRes, error)
	// ListOAuthTokens implements list_oauth_tokens operation.
	//
	// List User Tokens.
	//
	// GET /api/v1/oauth/tokens
	ListOAuthTokens(ctx context.Context) (ListOAuthTokensRes, error)
	// ListOrphanedEntities implements list_orphaned_entities operation.
	//
	// Lists all entities marked as orphans across all namespaces. Requires 'read:entities' permission.
	//
	// GET /api/v1/entities/orphans
	ListOrphanedEntities(ctx context.Context, params ListOrphanedEntitiesParams) (ListOrphanedEntitiesRes, error)
	// ListPrompts implements list_prompts operation.
	//
	// List all prompts for the environment.
	//
	// GET /api/v1/prompts
	ListPrompts(ctx context.Context, params ListPromptsParams) (ListPromptsRes, error)
	// MigrateAllDeprecatedConfigs implements migrate_all_deprecated_configs operation.
	//
	// Batch migrate all configs using deprecated versions.
	//
	// POST /api/v1/discovery/versions/migrate-all
	MigrateAllDeprecatedConfigs(ctx context.Context, params MigrateAllDeprecatedConfigsParams) (MigrateAllDeprecatedConfigsRes, error)
	// MigrateProviderConfig implements migrate_provider_config operation.
	//
	// Migrate a specific provider config to the latest version.
	//
	// POST /api/v1/discovery/versions/{provider_id}/migrate
	MigrateProviderConfig(ctx context.Context, params MigrateProviderConfigParams) (MigrateProviderConfigRes, error)
	// PostChatMessages implements post_chat_messages operation.
	//
	// Post Chat Messages.
	//
	// POST /api/v1/chats/{chat_id}/messages
	PostChatMessages(ctx context.Context, req []ChatMessageCreate, params PostChatMessagesParams) (PostChatMessagesRes, error)
	// RevokeOAuthToken implements revoke_oauth_token operation.
	//
	// Revoke Token.
	//
	// DELETE /api/v1/oauth/tokens/{service_name}
	RevokeOAuthToken(ctx context.Context, params RevokeOAuthTokenParams) (RevokeOAuthTokenRes, error)
	// UpdateChat implements update_chat operation.
	//
	// Update Chat.
	//
	// PUT /api/v1/chats/{chat_id}
	UpdateChat(ctx context.Context, req *ChatSessionUpdate, params UpdateChatParams) (UpdateChatRes, error)
	// UpdateConfiguredProvider implements update_configured_provider operation.
	//
	// Update a configured discovery provider.
	// Only provided fields will be updated. To update secrets, provide the full
	// config object with new secret values.
	//
	// PUT /api/v1/discovery/configured-providers/{provider_id}
	UpdateConfiguredProvider(ctx context.Context, req *ConfiguredProviderUpdate, params UpdateConfiguredProviderParams) (UpdateConfiguredProviderRes, error)
	// UpdateEnvironmentUser implements update_environment_user operation.
	//
	// Update an environment user's role.
	//
	// PUT /api/v1/environments/{environment_id}/users/{user_id}
	UpdateEnvironmentUser(ctx context.Context, req *EnvironmentUserUpdate, params UpdateEnvironmentUserParams) (UpdateEnvironmentUserRes, error)
	// UpdateMcpendpoint implements update_mcpendpoint operation.
	//
	// Update a specific MCP Endpoint configuration by ID.
	//
	// PUT /api/v1/mcp/endpoints/{mcpendpoint_id}
	UpdateMcpendpoint(ctx context.Context, req *MCPEndpointUpdate, params UpdateMcpendpointParams) (UpdateMcpendpointRes, error)
	// UpdateModel implements update_model operation.
	//
	// Update an existing AI model configuration by name.
	//
	// PUT /api/v1/models/{model_name}
	UpdateModel(ctx context.Context, req *ModelUpdate, params UpdateModelParams) (UpdateModelRes, error)
	// UpdateModelprovider implements update_modelprovider operation.
	//
	// Update a specific Model Provider configuration by ID.
	//
	// PUT /api/v1/models/providers/{provider_id}
	UpdateModelprovider(ctx context.Context, req *ModelProviderUpdate, params UpdateModelproviderParams) (UpdateModelproviderRes, error)
	// UpdateOAuthService implements update_oauth_service operation.
	//
	// Update Oauth Service.
	//
	// PUT /api/v1/oauth/services/{service_id}
	UpdateOAuthService(ctx context.Context, req *OAuthServiceUpdate, params UpdateOAuthServiceParams) (UpdateOAuthServiceRes, error)
	// UpdatePrompt implements update_prompt operation.
	//
	// Update a specific prompt by ID.
	//
	// PUT /api/v1/prompts/{prompt_id}
	UpdatePrompt(ctx context.Context, req *PromptUpdate, params UpdatePromptParams) (UpdatePromptRes, error)
	// UpdateToken implements update_token operation.
	//
	// Update a specific API token by ID.
	//
	// PUT /api/v1/tokens/{token_id}
	UpdateToken(ctx context.Context, req *ApiTokenUpdate, params UpdateTokenParams) (UpdateTokenRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
