// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// OAuth2PasswordBearer provides OAuth2PasswordBearer security value.
	OAuth2PasswordBearer(ctx context.Context, operationName OperationName) (OAuth2PasswordBearer, error)
}

func (s *Client) securityOAuth2PasswordBearer(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.OAuth2PasswordBearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"OAuth2PasswordBearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
