// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *ApiTokenResponse) setDefaults() {
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatSession) setDefaults() {
	{
		val := ChatVisibility("private")
		s.Visibility.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatSessionCreate) setDefaults() {
	{
		val := ChatVisibility("private")
		s.Visibility.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatSessionUpdate) setDefaults() {
	{
		val := ChatVisibility("private")
		s.Visibility.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityDefinitionResponse) setDefaults() {
	{
		val := string("v1")
		s.Name.SetTo(val)
	}
	{
		val := bool(true)
		s.Storage.SetTo(val)
	}
	{
		val := bool(true)
		s.Served.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityDefinitionSpec) setDefaults() {
	{
		val := string("v1")
		s.Name.SetTo(val)
	}
	{
		val := bool(true)
		s.Storage.SetTo(val)
	}
	{
		val := bool(true)
		s.Served.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityReference) setDefaults() {
	{
		val := string("default")
		s.Namespace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityReferenceResponse) setDefaults() {
	{
		val := string("default")
		s.Namespace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityRelation) setDefaults() {
	{
		val := string("default")
		s.Namespace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityRelationResponse) setDefaults() {
	{
		val := string("default")
		s.Namespace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EnvironmentUserCreate) setDefaults() {
	{
		val := string("org:member")
		s.Role.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EnvironmentUserInvite) setDefaults() {
	{
		val := string("org:member")
		s.Role.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MCPEndpointCreate) setDefaults() {
	{
		val := bool(false)
		s.DevgraphAuth.SetTo(val)
	}
	{
		val := bool(false)
		s.SupportsResources.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MCPEndpointResponse) setDefaults() {
	{
		val := bool(false)
		s.DevgraphAuth.SetTo(val)
	}
	{
		val := bool(false)
		s.SupportsResources.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelCreate) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ModelResponse) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OAuthServiceCreate) setDefaults() {
	{
		val := bool(true)
		s.IsActive.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OpenAIModelProviderCreate) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OpenAIModelProviderResponse) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *XAIModelProviderCreate) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *XAIModelProviderResponse) setDefaults() {
	{
		val := bool(false)
		s.Default.SetTo(val)
	}
}
