// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleOAuth2PasswordBearer handles OAuth2PasswordBearer security.
	HandleOAuth2PasswordBearer(ctx context.Context, operationName OperationName, t OAuth2PasswordBearer) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var oauth2ScopesOAuth2PasswordBearer = map[string][]string{
	BulkInviteEnvironmentUsersOperation:                     []string{},
	CheckEntitlementOperation:                               []string{},
	CleanupOrphanedEntitiesOperation:                        []string{},
	CreateChatOperation:                                     []string{},
	CreateChatSuggestionOperation:                           []string{},
	CreateChatTitleOperation:                                []string{},
	CreateConfiguredProviderOperation:                       []string{},
	CreateEntitiesBulkOperation:                             []string{},
	CreateEntityOperation:                                   []string{},
	CreateEntityDefinitionOperation:                         []string{},
	CreateEntityRelationOperation:                           []string{},
	CreateEntityRelationsBulkOperation:                      []string{},
	CreateEnvironmentOperation:                              []string{},
	CreateEnvironmentUserOperation:                          []string{},
	CreateMcpToolAssociationOperation:                       []string{},
	CreateMcpendpointOperation:                              []string{},
	CreateModelOperation:                                    []string{},
	CreateModelproviderOperation:                            []string{},
	CreateOAuthServiceOperation:                             []string{},
	CreatePromptOperation:                                   []string{},
	CreateTokenOperation:                                    []string{},
	DeleteChatOperation:                                     []string{},
	DeleteChatSuggestionOperation:                           []string{},
	DeleteChatsBulkOperation:                                []string{},
	DeleteConfiguredProviderOperation:                       []string{},
	DeleteEntityOperation:                                   []string{},
	DeleteEntityDefinitionOperation:                         []string{},
	DeleteEntityRelationOperation:                           []string{},
	DeleteEnvironmentOperation:                              []string{},
	DeleteEnvironmentInvitationOperation:                    []string{},
	DeleteEnvironmentUserOperation:                          []string{},
	DeleteMcpToolAssociationOperation:                       []string{},
	DeleteMcpendpointOperation:                              []string{},
	DeleteModelOperation:                                    []string{},
	DeleteModelproviderOperation:                            []string{},
	DeleteOAuthServiceOperation:                             []string{},
	DeletePromptOperation:                                   []string{},
	DeleteTokenOperation:                                    []string{},
	ExchangeOAuthTokenOperation:                             []string{},
	GetAllProviderVersionsOperation:                         []string{},
	GetChatOperation:                                        []string{},
	GetChatMessagesOperation:                                []string{},
	GetChatsOperation:                                       []string{},
	GetConfiguredProviderOperation:                          []string{},
	GetDeprecatedProviderConfigsOperation:                   []string{},
	GetDiscoveryProviderConfigSchemaOperation:               []string{},
	GetEntitiesOperation:                                    []string{},
	GetEntitlementsOperation:                                []string{},
	GetEntityByUIDOperation:                                 []string{},
	GetEntityDefinitionsOperation:                           []string{},
	GetEntityToolsOperation:                                 []string{},
	GetEnvironmentDiscoverySettingsOperation:                []string{},
	GetEnvironmentStatusOperation:                           []string{},
	GetEnvironmentUserOperation:                             []string{},
	GetEnvironmentsOperation:                                []string{},
	GetMcpEndpointEntityTypesOperation:                      []string{},
	GetMcpendpointOperation:                                 []string{},
	GetMcpendpointsOperation:                                []string{},
	GetModelOperation:                                       []string{},
	GetModelproviderOperation:                               []string{},
	GetModelprovidersOperation:                              []string{},
	GetModelsOperation:                                      []string{},
	GetOAuthAuthorizationURLOperation:                       []string{},
	GetOAuthServiceOperation:                                []string{},
	GetPendingInvitationsOperation:                          []string{},
	GetPromptOperation:                                      []string{},
	GetRendererAllowlistAPIV1RenderersAllowlistGetOperation: []string{},
	GetSubscriptionsOperation:                               []string{},
	GetSystemDefaultPromptOperation:                         []string{},
	GetTokensOperation:                                      []string{},
	InviteEnvironmentUserOperation:                          []string{},
	ListAllMcpToolsOperation:                                []string{},
	ListChatSuggestionsOperation:                            []string{},
	ListConfiguredProvidersOperation:                        []string{},
	ListDiscoveryProvidersOperation:                         []string{},
	ListEnvironmentUsersOperation:                           []string{},
	ListMcpendpointToolsOperation:                           []string{},
	ListOAuthServicesOperation:                              []string{},
	ListOAuthTokensOperation:                                []string{},
	ListOrphanedEntitiesOperation:                           []string{},
	ListPromptsOperation:                                    []string{},
	MigrateAllDeprecatedConfigsOperation:                    []string{},
	MigrateProviderConfigOperation:                          []string{},
	PostChatMessagesOperation:                               []string{},
	RevokeOAuthTokenOperation:                               []string{},
	UpdateChatOperation:                                     []string{},
	UpdateConfiguredProviderOperation:                       []string{},
	UpdateEnvironmentDiscoverySettingsOperation:             []string{},
	UpdateEnvironmentUserOperation:                          []string{},
	UpdateMcpendpointOperation:                              []string{},
	UpdateModelOperation:                                    []string{},
	UpdateModelproviderOperation:                            []string{},
	UpdateOAuthServiceOperation:                             []string{},
	UpdatePromptOperation:                                   []string{},
	UpdateTokenOperation:                                    []string{},
}

func (s *Server) securityOAuth2PasswordBearer(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t OAuth2PasswordBearer
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Scopes = oauth2ScopesOAuth2PasswordBearer[operationName]
	rctx, err := s.sec.HandleOAuth2PasswordBearer(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// OAuth2PasswordBearer provides OAuth2PasswordBearer security value.
	OAuth2PasswordBearer(ctx context.Context, operationName OperationName) (OAuth2PasswordBearer, error)
}

func (s *Client) securityOAuth2PasswordBearer(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.OAuth2PasswordBearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"OAuth2PasswordBearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
