// Code generated by ogen, DO NOT EDIT.
package v1

type BulkInviteEnvironmentUsersRes interface {
	bulkInviteEnvironmentUsersRes()
}

type CheckEntitlementRes interface {
	checkEntitlementRes()
}

type CleanupOrphanedEntitiesRes interface {
	cleanupOrphanedEntitiesRes()
}

type CreateChatRes interface {
	createChatRes()
}

type CreateChatSuggestionRes interface {
	createChatSuggestionRes()
}

type CreateChatTitleRes interface {
	createChatTitleRes()
}

type CreateConfiguredProviderRes interface {
	createConfiguredProviderRes()
}

type CreateEntitiesBulkRes interface {
	createEntitiesBulkRes()
}

type CreateEntityDefinitionRes interface {
	createEntityDefinitionRes()
}

type CreateEntityRelationRes interface {
	createEntityRelationRes()
}

type CreateEntityRelationsBulkRes interface {
	createEntityRelationsBulkRes()
}

type CreateEntityRes interface {
	createEntityRes()
}

type CreateEnvironmentRes interface {
	createEnvironmentRes()
}

type CreateEnvironmentUserRes interface {
	createEnvironmentUserRes()
}

type CreateMcpToolAssociationRes interface {
	createMcpToolAssociationRes()
}

type CreateMcpendpointRes interface {
	createMcpendpointRes()
}

type CreateModelRes interface {
	createModelRes()
}

type CreateModelproviderRes interface {
	createModelproviderRes()
}

type CreateOAuthServiceRes interface {
	createOAuthServiceRes()
}

type CreatePromptRes interface {
	createPromptRes()
}

type CreateTokenRes interface {
	createTokenRes()
}

type DeleteChatRes interface {
	deleteChatRes()
}

type DeleteChatSuggestionRes interface {
	deleteChatSuggestionRes()
}

type DeleteChatsBulkRes interface {
	deleteChatsBulkRes()
}

type DeleteConfiguredProviderRes interface {
	deleteConfiguredProviderRes()
}

type DeleteEntityDefinitionRes interface {
	deleteEntityDefinitionRes()
}

type DeleteEntityRelationRes interface {
	deleteEntityRelationRes()
}

type DeleteEntityRes interface {
	deleteEntityRes()
}

type DeleteEnvironmentInvitationRes interface {
	deleteEnvironmentInvitationRes()
}

type DeleteEnvironmentRes interface {
	deleteEnvironmentRes()
}

type DeleteEnvironmentUserRes interface {
	deleteEnvironmentUserRes()
}

type DeleteMcpToolAssociationRes interface {
	deleteMcpToolAssociationRes()
}

type DeleteMcpendpointRes interface {
	deleteMcpendpointRes()
}

type DeleteModelRes interface {
	deleteModelRes()
}

type DeleteModelproviderRes interface {
	deleteModelproviderRes()
}

type DeleteOAuthServiceRes interface {
	deleteOAuthServiceRes()
}

type DeletePromptRes interface {
	deletePromptRes()
}

type DeleteTokenRes interface {
	deleteTokenRes()
}

type ExchangeOAuthTokenRes interface {
	exchangeOAuthTokenRes()
}

type GetAllProviderVersionsRes interface {
	getAllProviderVersionsRes()
}

type GetChatMessagesRes interface {
	getChatMessagesRes()
}

type GetChatRes interface {
	getChatRes()
}

type GetChatsRes interface {
	getChatsRes()
}

type GetConfiguredProviderRes interface {
	getConfiguredProviderRes()
}

type GetDeprecatedProviderConfigsRes interface {
	getDeprecatedProviderConfigsRes()
}

type GetDiscoveryProviderConfigSchemaRes interface {
	getDiscoveryProviderConfigSchemaRes()
}

type GetEntitiesRes interface {
	getEntitiesRes()
}

type GetEntitlementsRes interface {
	getEntitlementsRes()
}

type GetEntityByUIDRes interface {
	getEntityByUIDRes()
}

type GetEntityDefinitionsRes interface {
	getEntityDefinitionsRes()
}

type GetEntityRes interface {
	getEntityRes()
}

type GetEntityToolsRes interface {
	getEntityToolsRes()
}

type GetEnvironmentStatusRes interface {
	getEnvironmentStatusRes()
}

type GetEnvironmentUserRes interface {
	getEnvironmentUserRes()
}

type GetEnvironmentsRes interface {
	getEnvironmentsRes()
}

type GetMcpEndpointEntityTypesRes interface {
	getMcpEndpointEntityTypesRes()
}

type GetMcpendpointRes interface {
	getMcpendpointRes()
}

type GetMcpendpointsRes interface {
	getMcpendpointsRes()
}

type GetModelRes interface {
	getModelRes()
}

type GetModelproviderRes interface {
	getModelproviderRes()
}

type GetModelprovidersRes interface {
	getModelprovidersRes()
}

type GetModelsRes interface {
	getModelsRes()
}

type GetOAuthAuthorizationURLRes interface {
	getOAuthAuthorizationURLRes()
}

type GetOAuthServiceRes interface {
	getOAuthServiceRes()
}

type GetPendingInvitationsRes interface {
	getPendingInvitationsRes()
}

type GetPromptRes interface {
	getPromptRes()
}

type GetSubscriptionsRes interface {
	getSubscriptionsRes()
}

type GetSystemDefaultPromptRes interface {
	getSystemDefaultPromptRes()
}

type GetTokensRes interface {
	getTokensRes()
}

type InviteEnvironmentUserRes interface {
	inviteEnvironmentUserRes()
}

type ListAllMcpToolsRes interface {
	listAllMcpToolsRes()
}

type ListChatSuggestionsRes interface {
	listChatSuggestionsRes()
}

type ListConfiguredProvidersRes interface {
	listConfiguredProvidersRes()
}

type ListDiscoveryProvidersRes interface {
	listDiscoveryProvidersRes()
}

type ListEnvironmentUsersRes interface {
	listEnvironmentUsersRes()
}

type ListMcpendpointToolsRes interface {
	listMcpendpointToolsRes()
}

type ListOAuthServicesRes interface {
	listOAuthServicesRes()
}

type ListOAuthTokensRes interface {
	listOAuthTokensRes()
}

type ListOrphanedEntitiesRes interface {
	listOrphanedEntitiesRes()
}

type ListPromptsRes interface {
	listPromptsRes()
}

type MigrateAllDeprecatedConfigsRes interface {
	migrateAllDeprecatedConfigsRes()
}

type MigrateProviderConfigRes interface {
	migrateProviderConfigRes()
}

type PostChatMessagesRes interface {
	postChatMessagesRes()
}

type RevokeOAuthTokenRes interface {
	revokeOAuthTokenRes()
}

type UpdateChatRes interface {
	updateChatRes()
}

type UpdateConfiguredProviderRes interface {
	updateConfiguredProviderRes()
}

type UpdateEnvironmentUserRes interface {
	updateEnvironmentUserRes()
}

type UpdateMcpendpointRes interface {
	updateMcpendpointRes()
}

type UpdateModelRes interface {
	updateModelRes()
}

type UpdateModelproviderRes interface {
	updateModelproviderRes()
}

type UpdateOAuthServiceRes interface {
	updateOAuthServiceRes()
}

type UpdatePromptRes interface {
	updatePromptRes()
}

type UpdateTokenRes interface {
	updateTokenRes()
}
