// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// BulkInviteEnvironmentUsers implements bulk_invite_environment_users operation.
//
// Bulk invite multiple users to an environment (organization).
//
// POST /api/v1/environments/{environment_id}/users/bulk-invite
func (UnimplementedHandler) BulkInviteEnvironmentUsers(ctx context.Context, req *EnvironmentUserBulkInvite, params BulkInviteEnvironmentUsersParams) (r BulkInviteEnvironmentUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CheckEntitlement implements check_entitlement operation.
//
// Check a specific entitlement for the authenticated user.
// For numeric limits (e.g., max_environments), returns current usage and remaining quota.
// For boolean features (e.g., enable_sso), returns whether the feature is enabled.
//
// GET /api/v1/entitlements/check/{entitlement_type}
func (UnimplementedHandler) CheckEntitlement(ctx context.Context, params CheckEntitlementParams) (r CheckEntitlementRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CleanupOrphanedEntities implements cleanup_orphaned_entities operation.
//
// Delete all entities marked as orphans. Requires 'delete:entities' permission.
//
// DELETE /api/v1/entities/orphans
func (UnimplementedHandler) CleanupOrphanedEntities(ctx context.Context, params CleanupOrphanedEntitiesParams) (r CleanupOrphanedEntitiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateChat implements create_chat operation.
//
// Create Chat.
//
// POST /api/v1/chats/
func (UnimplementedHandler) CreateChat(ctx context.Context, req *ChatSessionCreate) (r CreateChatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateChatSuggestion implements create_chat_suggestion operation.
//
// Create a new chat suggestion for the environment.
//
// POST /api/v1/chats/suggestions
func (UnimplementedHandler) CreateChatSuggestion(ctx context.Context, req *ChatSuggestionCreate) (r CreateChatSuggestionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateChatTitle implements create_chat_title operation.
//
// Generate a title for a chat based on the first message.
//
// POST /api/v1/chats/title
func (UnimplementedHandler) CreateChatTitle(ctx context.Context, req *ChatTitleRequest) (r CreateChatTitleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateConfiguredProvider implements create_configured_provider operation.
//
// Create a new configured discovery provider.
// The provider configuration (including secrets) will be encrypted and stored.
//
// POST /api/v1/discovery/configured-providers
func (UnimplementedHandler) CreateConfiguredProvider(ctx context.Context, req *ConfiguredProviderCreate) (r CreateConfiguredProviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEntitiesBulk implements create_entities_bulk operation.
//
// Creates multiple entities in a single request with concurrent processing. Provides detailed
// success/failure information for each entity. Requires 'create:entities' permission.
//
// POST /api/v1/entities/bulk
func (UnimplementedHandler) CreateEntitiesBulk(ctx context.Context, req []Entity, params CreateEntitiesBulkParams) (r CreateEntitiesBulkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEntity implements create_entity operation.
//
// Creates a new entity based on the specified group, version, namespace, and kind. Requires
// 'create:entities' permission.
//
// POST /api/v1/entities/{group}/{version}/namespace/{namespace}/{plural}
func (UnimplementedHandler) CreateEntity(ctx context.Context, req *Entity, params CreateEntityParams) (r CreateEntityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEntityDefinition implements create_entity_definition operation.
//
// Create a new entity definition with schema and storage configuration.
//
// POST /api/v1/entities/definitions
func (UnimplementedHandler) CreateEntityDefinition(ctx context.Context, req *EntityDefinitionSpec) (r CreateEntityDefinitionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEntityRelation implements create_entity_relation operation.
//
// Create Entity Relation.
//
// POST /api/v1/entities/relations
func (UnimplementedHandler) CreateEntityRelation(ctx context.Context, req *EntityRelation, params CreateEntityRelationParams) (r CreateEntityRelationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEntityRelationsBulk implements create_entity_relations_bulk operation.
//
// Creates multiple entity relations in a single request. Provides detailed success/failure
// information for each relation. Requires 'create:entityrelations' permission.
//
// POST /api/v1/entities/relations/bulk
func (UnimplementedHandler) CreateEntityRelationsBulk(ctx context.Context, req *BulkEntityRelationCreateRequest) (r CreateEntityRelationsBulkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEnvironment implements create_environment operation.
//
// Create Environment.
//
// POST /api/v1/environments
func (UnimplementedHandler) CreateEnvironment(ctx context.Context, req *EnvironmentCreate) (r CreateEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEnvironmentUser implements create_environment_user operation.
//
// Create a new environment user by adding them to the Clerk organization.
//
// POST /api/v1/environments/{environment_id}/users
func (UnimplementedHandler) CreateEnvironmentUser(ctx context.Context, req *EnvironmentUserCreate, params CreateEnvironmentUserParams) (r CreateEnvironmentUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMcpToolAssociation implements create_mcp_tool_association operation.
//
// Create an association between an MCP tool and an entity definition.
//
// POST /api/v1/mcp/tool-associations
func (UnimplementedHandler) CreateMcpToolAssociation(ctx context.Context, req *MCPToolEntityAssociationCreate) (r CreateMcpToolAssociationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMcpendpoint implements create_mcpendpoint operation.
//
// Create a new MCP Endpoint configuration.
//
// POST /api/v1/mcp/endpoints
func (UnimplementedHandler) CreateMcpendpoint(ctx context.Context, req *MCPEndpointCreate) (r CreateMcpendpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateModel implements create_model operation.
//
// Create a new AI model configuration with provider details in the environment.
//
// POST /api/v1/models
func (UnimplementedHandler) CreateModel(ctx context.Context, req *ModelCreate) (r CreateModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateModelprovider implements create_modelprovider operation.
//
// Create a new Model Provider configuration.
//
// POST /api/v1/models/providers
func (UnimplementedHandler) CreateModelprovider(ctx context.Context, req *ModelProviderCreate) (r CreateModelproviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOAuthService implements create_oauth_service operation.
//
// Create Oauth Service.
//
// POST /api/v1/oauth/services
func (UnimplementedHandler) CreateOAuthService(ctx context.Context, req *OAuthServiceCreate) (r CreateOAuthServiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePrompt implements create_prompt operation.
//
// Create a new prompt for the environment.
//
// POST /api/v1/prompts
func (UnimplementedHandler) CreatePrompt(ctx context.Context, req *PromptCreate) (r CreatePromptRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateToken implements create_token operation.
//
// Create Token.
//
// POST /api/v1/tokens
func (UnimplementedHandler) CreateToken(ctx context.Context, req *ApiTokenCreate) (r CreateTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteChat implements delete_chat operation.
//
// Delete Chat.
//
// DELETE /api/v1/chats/{chat_id}
func (UnimplementedHandler) DeleteChat(ctx context.Context, params DeleteChatParams) (r DeleteChatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteChatSuggestion implements delete_chat_suggestion operation.
//
// Delete a chat suggestion. Can only delete user's own suggestions (not system ones).
//
// DELETE /api/v1/chats/suggestions/{suggestion_id}
func (UnimplementedHandler) DeleteChatSuggestion(ctx context.Context, params DeleteChatSuggestionParams) (r DeleteChatSuggestionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteChatsBulk implements delete_chats_bulk operation.
//
// Bulk delete multiple chat sessions.
//
// DELETE /api/v1/chats/
func (UnimplementedHandler) DeleteChatsBulk(ctx context.Context, req *BulkDeleteRequest) (r DeleteChatsBulkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteConfiguredProvider implements delete_configured_provider operation.
//
// Delete a configured discovery provider.
//
// DELETE /api/v1/discovery/configured-providers/{provider_id}
func (UnimplementedHandler) DeleteConfiguredProvider(ctx context.Context, params DeleteConfiguredProviderParams) (r DeleteConfiguredProviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEntity implements delete_entity operation.
//
// Deletes a specific entity from the ontology. Requires 'delete:entities' permission.
//
// DELETE /api/v1/entities/{group}/{version}/{kind}/{namespace}/{name}
func (UnimplementedHandler) DeleteEntity(ctx context.Context, params DeleteEntityParams) (r DeleteEntityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEntityDefinition implements delete_entity_definition operation.
//
// Deletes an entity definition and all its versions. Requires 'delete:entitydefinitions' permission.
//
// DELETE /api/v1/entities/definitions/{definition_id}
func (UnimplementedHandler) DeleteEntityDefinition(ctx context.Context, params DeleteEntityDefinitionParams) (r DeleteEntityDefinitionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEntityRelation implements delete_entity_relation operation.
//
// Deletes a specific relation between two entities. Requires 'delete:entityrelations' permission.
//
// DELETE /api/v1/entities/relations
func (UnimplementedHandler) DeleteEntityRelation(ctx context.Context, req *EntityRelation, params DeleteEntityRelationParams) (r DeleteEntityRelationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEnvironment implements delete_environment operation.
//
// Soft delete an environment.
// This marks the environment as deleted (sets deleted_at timestamp) which triggers
// the Kubernetes controller to clean up all associated resources (namespace, database, etc.).
// The environment record is retained for the configured retention period for potential recovery.
// For permanent GDPR-compliant deletion, use the Admin API endpoint.
//
// DELETE /api/v1/environments/{env_id}
func (UnimplementedHandler) DeleteEnvironment(ctx context.Context, params DeleteEnvironmentParams) (r DeleteEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEnvironmentInvitation implements delete_environment_invitation operation.
//
// Revoke a pending invitation to an environment (organization).
//
// DELETE /api/v1/environments/{environment_id}/users/invitations/{invitation_id}
func (UnimplementedHandler) DeleteEnvironmentInvitation(ctx context.Context, params DeleteEnvironmentInvitationParams) (r DeleteEnvironmentInvitationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEnvironmentUser implements delete_environment_user operation.
//
// Remove a user from an environment (organization).
//
// DELETE /api/v1/environments/{environment_id}/users/{user_id}
func (UnimplementedHandler) DeleteEnvironmentUser(ctx context.Context, params DeleteEnvironmentUserParams) (r DeleteEnvironmentUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMcpToolAssociation implements delete_mcp_tool_association operation.
//
// Delete an MCP tool-entity association.
//
// DELETE /api/v1/mcp/tool-associations/{association_id}
func (UnimplementedHandler) DeleteMcpToolAssociation(ctx context.Context, params DeleteMcpToolAssociationParams) (r DeleteMcpToolAssociationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMcpendpoint implements delete_mcpendpoint operation.
//
// Delete a specific MCP Endpoint configuration by ID.
//
// DELETE /api/v1/mcp/endpoints/{mcpendpoint_id}
func (UnimplementedHandler) DeleteMcpendpoint(ctx context.Context, params DeleteMcpendpointParams) (r DeleteMcpendpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteModel implements delete_model operation.
//
// Soft delete an AI model configuration by name.
//
// DELETE /api/v1/models/{model_name}
func (UnimplementedHandler) DeleteModel(ctx context.Context, params DeleteModelParams) (r DeleteModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteModelprovider implements delete_modelprovider operation.
//
// Delete a specific Model Provider configuration by ID.
//
// DELETE /api/v1/models/providers/{provider_id}
func (UnimplementedHandler) DeleteModelprovider(ctx context.Context, params DeleteModelproviderParams) (r DeleteModelproviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOAuthService implements delete_oauth_service operation.
//
// Delete Oauth Service.
//
// DELETE /api/v1/oauth/services/{service_id}
func (UnimplementedHandler) DeleteOAuthService(ctx context.Context, params DeleteOAuthServiceParams) (r DeleteOAuthServiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePrompt implements delete_prompt operation.
//
// Delete a specific prompt by ID.
//
// DELETE /api/v1/prompts/{prompt_id}
func (UnimplementedHandler) DeletePrompt(ctx context.Context, params DeletePromptParams) (r DeletePromptRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteToken implements delete_token operation.
//
// Delete a specific API token by ID.
//
// DELETE /api/v1/tokens/{token_id}
func (UnimplementedHandler) DeleteToken(ctx context.Context, params DeleteTokenParams) (r DeleteTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ExchangeOAuthToken implements exchange_oauth_token operation.
//
// Exchange Code For Token.
//
// POST /api/v1/oauth/token
func (UnimplementedHandler) ExchangeOAuthToken(ctx context.Context, req *OAuthTokenExchange) (r ExchangeOAuthTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllProviderVersions implements get_all_provider_versions operation.
//
// Get version support info for all available provider types.
//
// GET /api/v1/discovery/versions
func (UnimplementedHandler) GetAllProviderVersions(ctx context.Context) (r GetAllProviderVersionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChat implements get_chat operation.
//
// Get Chat.
//
// GET /api/v1/chats/{chat_id}
func (UnimplementedHandler) GetChat(ctx context.Context, params GetChatParams) (r GetChatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChatMessages implements get_chat_messages operation.
//
// Get Chat Messages.
//
// GET /api/v1/chats/{chat_id}/messages
func (UnimplementedHandler) GetChatMessages(ctx context.Context, params GetChatMessagesParams) (r GetChatMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChats implements get_chats operation.
//
// Get Chats.
//
// GET /api/v1/chats/
func (UnimplementedHandler) GetChats(ctx context.Context, params GetChatsParams) (r GetChatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConfiguredProvider implements get_configured_provider operation.
//
// Get a specific configured discovery provider.
// Secrets in the provider configuration are masked.
//
// GET /api/v1/discovery/configured-providers/{provider_id}
func (UnimplementedHandler) GetConfiguredProvider(ctx context.Context, params GetConfiguredProviderParams) (r GetConfiguredProviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDeprecatedProviderConfigs implements get_deprecated_provider_configs operation.
//
// Get all provider instances using deprecated config versions.
//
// GET /api/v1/discovery/versions/deprecated
func (UnimplementedHandler) GetDeprecatedProviderConfigs(ctx context.Context, params GetDeprecatedProviderConfigsParams) (r GetDeprecatedProviderConfigsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDiscoveryProviderConfigSchema implements get_discovery_provider_config_schema operation.
//
// Get the configuration schema for a specific discovery provider type.
// Args:
// provider_type: The type identifier of the provider (e.g., 'github', 'gitlab')
// Returns:
// JSON schema for the provider's configuration.
//
// GET /api/v1/discovery/providers/{provider_type}/config-schema
func (UnimplementedHandler) GetDiscoveryProviderConfigSchema(ctx context.Context, params GetDiscoveryProviderConfigSchemaParams) (r GetDiscoveryProviderConfigSchemaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEntities implements get_entities operation.
//
// Retrieves entities from the ontology, optionally filtered by field selectors. Field selectors use
// dot notation for nested properties (e.g., 'spec.metadata.owner=team-a'). Requires 'read:entities'
// permission.
//
// GET /api/v1/entities/
func (UnimplementedHandler) GetEntities(ctx context.Context, params GetEntitiesParams) (r GetEntitiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEntitlements implements get_entitlements operation.
//
// Get all entitlements and current usage for the authenticated user.
//
// GET /api/v1/entitlements
func (UnimplementedHandler) GetEntitlements(ctx context.Context) (r GetEntitlementsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEntity implements get_entity operation.
//
// Fetches a specific entity based on group, version, namespace, plural, and name, including related
// entities and relations. Requires 'read:entities' permission.
//
// GET /api/v1/entities/{group}/{version}/{kind}/{namespace}/{name}
func (UnimplementedHandler) GetEntity(ctx context.Context, params GetEntityParams) (r GetEntityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEntityByUID implements get_entity_by_uid operation.
//
// Fetches a specific entity by its unique identifier (UID), including related entities and relations.
//
//	Requires 'read:entities' permission.
//
// GET /api/v1/entities/uid/{uid}
func (UnimplementedHandler) GetEntityByUID(ctx context.Context, params GetEntityByUIDParams) (r GetEntityByUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEntityDefinitions implements get_entity_definitions operation.
//
// Fetches a list of all entity definitions with versions, ordered by group and kind.
//
// GET /api/v1/entities/definitions
func (UnimplementedHandler) GetEntityDefinitions(ctx context.Context) (r GetEntityDefinitionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEntityTools implements get_entity_tools operation.
//
// Get all MCP tools associated with an entity definition.
//
// GET /api/v1/mcp/entity-definitions/{entity_definition_id}/tools
func (UnimplementedHandler) GetEntityTools(ctx context.Context, params GetEntityToolsParams) (r GetEntityToolsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironmentStatus implements get_environment_status operation.
//
// Get Environment Status.
//
// GET /api/v1/environments/{env_id}/status
func (UnimplementedHandler) GetEnvironmentStatus(ctx context.Context, params GetEnvironmentStatusParams) (r GetEnvironmentStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironmentUser implements get_environment_user operation.
//
// Get a specific environment user.
//
// GET /api/v1/environments/{environment_id}/users/{user_id}
func (UnimplementedHandler) GetEnvironmentUser(ctx context.Context, params GetEnvironmentUserParams) (r GetEnvironmentUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironments implements get_environments operation.
//
// Get Environments.
//
// GET /api/v1/environments
func (UnimplementedHandler) GetEnvironments(ctx context.Context) (r GetEnvironmentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMcpEndpointEntityTypes implements get_mcp_endpoint_entity_types operation.
//
// Get all entity types associated with an MCP endpoint's tools.
//
// GET /api/v1/mcp/endpoints/{mcpendpoint_name}/entity-types
func (UnimplementedHandler) GetMcpEndpointEntityTypes(ctx context.Context, params GetMcpEndpointEntityTypesParams) (r GetMcpEndpointEntityTypesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMcpendpoint implements get_mcpendpoint operation.
//
// Get a specific MCP Endpoint configuration by ID.
//
// GET /api/v1/mcp/endpoints/{mcpendpoint_id}
func (UnimplementedHandler) GetMcpendpoint(ctx context.Context, params GetMcpendpointParams) (r GetMcpendpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMcpendpoints implements get_mcpendpoints operation.
//
// List all MCP Endpoint configurations for the authenticated user and environment.
//
// GET /api/v1/mcp/endpoints
func (UnimplementedHandler) GetMcpendpoints(ctx context.Context) (r GetMcpendpointsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetModel implements get_model operation.
//
// Retrieve a specific AI model configuration by name.
//
// GET /api/v1/models/{model_name}
func (UnimplementedHandler) GetModel(ctx context.Context, params GetModelParams) (r GetModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetModelprovider implements get_modelprovider operation.
//
// Get a specific Model Provider configuration by ID.
//
// GET /api/v1/models/providers/{provider_id}
func (UnimplementedHandler) GetModelprovider(ctx context.Context, params GetModelproviderParams) (r GetModelproviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetModelproviders implements get_modelproviders operation.
//
// List all Model Provider configurations for the authenticated user and environment.
//
// GET /api/v1/models/providers
func (UnimplementedHandler) GetModelproviders(ctx context.Context) (r GetModelprovidersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetModels implements get_models operation.
//
// Retrieve all AI model configurations for the current environment.
//
// GET /api/v1/models
func (UnimplementedHandler) GetModels(ctx context.Context) (r GetModelsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOAuthAuthorizationURL implements get_oauth_authorization_url operation.
//
// Get Authorization Url.
//
// POST /api/v1/oauth/authorize
func (UnimplementedHandler) GetOAuthAuthorizationURL(ctx context.Context, req *OAuthAuthorizationRequest) (r GetOAuthAuthorizationURLRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOAuthService implements get_oauth_service operation.
//
// Get Oauth Service.
//
// GET /api/v1/oauth/services/{service_id}
func (UnimplementedHandler) GetOAuthService(ctx context.Context, params GetOAuthServiceParams) (r GetOAuthServiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPendingInvitations implements get_pending_invitations operation.
//
// Get all pending invitations for an environment (users who have been invited but haven't joined
// yet).
//
// GET /api/v1/environments/{environment_id}/users/pending
func (UnimplementedHandler) GetPendingInvitations(ctx context.Context, params GetPendingInvitationsParams) (r GetPendingInvitationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPrompt implements get_prompt operation.
//
// Get a specific prompt by ID.
//
// GET /api/v1/prompts/{prompt_id}
func (UnimplementedHandler) GetPrompt(ctx context.Context, params GetPromptParams) (r GetPromptRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSubscriptions implements get_subscriptions operation.
//
// Get Subscriptions.
//
// GET /api/v1/subscriptions
func (UnimplementedHandler) GetSubscriptions(ctx context.Context) (r GetSubscriptionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSystemDefaultPrompt implements get_system_default_prompt operation.
//
// Get the built-in system default prompt.
//
// GET /api/v1/prompts/system-default
func (UnimplementedHandler) GetSystemDefaultPrompt(ctx context.Context) (r GetSystemDefaultPromptRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTokens implements get_tokens operation.
//
// Get all API tokens for the authenticated user.
//
// GET /api/v1/tokens
func (UnimplementedHandler) GetTokens(ctx context.Context) (r GetTokensRes, _ error) {
	return r, ht.ErrNotImplemented
}

// InviteEnvironmentUser implements invite_environment_user operation.
//
// Invite a user to an environment (organization).
//
// POST /api/v1/environments/{environment_id}/users/invite
func (UnimplementedHandler) InviteEnvironmentUser(ctx context.Context, req *EnvironmentUserInvite, params InviteEnvironmentUserParams) (r InviteEnvironmentUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListChatSuggestions implements list_chat_suggestions operation.
//
// List chat suggestions. Returns system-wide suggestions + environment/user-specific ones.
//
// GET /api/v1/chats/suggestions
func (UnimplementedHandler) ListChatSuggestions(ctx context.Context, params ListChatSuggestionsParams) (r ListChatSuggestionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListConfiguredProviders implements list_configured_providers operation.
//
// List all configured discovery providers for the current environment.
// Secrets in provider configurations are masked.
//
// GET /api/v1/discovery/configured-providers
func (UnimplementedHandler) ListConfiguredProviders(ctx context.Context) (r ListConfiguredProvidersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDiscoveryProviders implements list_discovery_providers operation.
//
// List all available discovery provider types with their configuration schemas.
// This endpoint discovers all registered discovery providers using the plugin system
// and returns their metadata including JSON schemas for configuration.
//
// GET /api/v1/discovery/providers
func (UnimplementedHandler) ListDiscoveryProviders(ctx context.Context) (r ListDiscoveryProvidersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListEnvironmentUsers implements list_environment_users operation.
//
// List all users in an environment (organization members).
//
// GET /api/v1/environments/{environment_id}/users
func (UnimplementedHandler) ListEnvironmentUsers(ctx context.Context, params ListEnvironmentUsersParams) (r ListEnvironmentUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMcpendpointTools implements list_mcpendpoint_tools operation.
//
// List all available tools from a specific MCP Endpoint.
// This interrogates the MCP server to discover its available tools.
//
// GET /api/v1/mcp/endpoints/{mcpendpoint_id}/tools
func (UnimplementedHandler) ListMcpendpointTools(ctx context.Context, params ListMcpendpointToolsParams) (r ListMcpendpointToolsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOAuthServices implements list_oauth_services operation.
//
// List Oauth Services.
//
// GET /api/v1/oauth/services
func (UnimplementedHandler) ListOAuthServices(ctx context.Context, params ListOAuthServicesParams) (r ListOAuthServicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOAuthTokens implements list_oauth_tokens operation.
//
// List User Tokens.
//
// GET /api/v1/oauth/tokens
func (UnimplementedHandler) ListOAuthTokens(ctx context.Context) (r ListOAuthTokensRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOrphanedEntities implements list_orphaned_entities operation.
//
// Lists all entities marked as orphans across all namespaces. Requires 'read:entities' permission.
//
// GET /api/v1/entities/orphans
func (UnimplementedHandler) ListOrphanedEntities(ctx context.Context, params ListOrphanedEntitiesParams) (r ListOrphanedEntitiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPrompts implements list_prompts operation.
//
// List all prompts for the environment.
//
// GET /api/v1/prompts
func (UnimplementedHandler) ListPrompts(ctx context.Context, params ListPromptsParams) (r ListPromptsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MigrateAllDeprecatedConfigs implements migrate_all_deprecated_configs operation.
//
// Batch migrate all configs using deprecated versions.
//
// POST /api/v1/discovery/versions/migrate-all
func (UnimplementedHandler) MigrateAllDeprecatedConfigs(ctx context.Context, params MigrateAllDeprecatedConfigsParams) (r MigrateAllDeprecatedConfigsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MigrateProviderConfig implements migrate_provider_config operation.
//
// Migrate a specific provider config to the latest version.
//
// POST /api/v1/discovery/versions/{provider_id}/migrate
func (UnimplementedHandler) MigrateProviderConfig(ctx context.Context, params MigrateProviderConfigParams) (r MigrateProviderConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostChatMessages implements post_chat_messages operation.
//
// Post Chat Messages.
//
// POST /api/v1/chats/{chat_id}/messages
func (UnimplementedHandler) PostChatMessages(ctx context.Context, req []ChatMessageCreate, params PostChatMessagesParams) (r PostChatMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeOAuthToken implements revoke_oauth_token operation.
//
// Revoke Token.
//
// DELETE /api/v1/oauth/tokens/{service_name}
func (UnimplementedHandler) RevokeOAuthToken(ctx context.Context, params RevokeOAuthTokenParams) (r RevokeOAuthTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateChat implements update_chat operation.
//
// Update Chat.
//
// PUT /api/v1/chats/{chat_id}
func (UnimplementedHandler) UpdateChat(ctx context.Context, req *ChatSessionUpdate, params UpdateChatParams) (r UpdateChatRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateConfiguredProvider implements update_configured_provider operation.
//
// Update a configured discovery provider.
// Only provided fields will be updated. To update secrets, provide the full
// config object with new secret values.
//
// PUT /api/v1/discovery/configured-providers/{provider_id}
func (UnimplementedHandler) UpdateConfiguredProvider(ctx context.Context, req *ConfiguredProviderUpdate, params UpdateConfiguredProviderParams) (r UpdateConfiguredProviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEnvironmentUser implements update_environment_user operation.
//
// Update an environment user's role.
//
// PUT /api/v1/environments/{environment_id}/users/{user_id}
func (UnimplementedHandler) UpdateEnvironmentUser(ctx context.Context, req *EnvironmentUserUpdate, params UpdateEnvironmentUserParams) (r UpdateEnvironmentUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMcpendpoint implements update_mcpendpoint operation.
//
// Update a specific MCP Endpoint configuration by ID.
//
// PUT /api/v1/mcp/endpoints/{mcpendpoint_id}
func (UnimplementedHandler) UpdateMcpendpoint(ctx context.Context, req *MCPEndpointUpdate, params UpdateMcpendpointParams) (r UpdateMcpendpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateModel implements update_model operation.
//
// Update an existing AI model configuration by name.
//
// PUT /api/v1/models/{model_name}
func (UnimplementedHandler) UpdateModel(ctx context.Context, req *ModelUpdate, params UpdateModelParams) (r UpdateModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateModelprovider implements update_modelprovider operation.
//
// Update a specific Model Provider configuration by ID.
//
// PUT /api/v1/models/providers/{provider_id}
func (UnimplementedHandler) UpdateModelprovider(ctx context.Context, req *ModelProviderUpdate, params UpdateModelproviderParams) (r UpdateModelproviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOAuthService implements update_oauth_service operation.
//
// Update Oauth Service.
//
// PUT /api/v1/oauth/services/{service_id}
func (UnimplementedHandler) UpdateOAuthService(ctx context.Context, req *OAuthServiceUpdate, params UpdateOAuthServiceParams) (r UpdateOAuthServiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePrompt implements update_prompt operation.
//
// Update a specific prompt by ID.
//
// PUT /api/v1/prompts/{prompt_id}
func (UnimplementedHandler) UpdatePrompt(ctx context.Context, req *PromptUpdate, params UpdatePromptParams) (r UpdatePromptRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateToken implements update_token operation.
//
// Update a specific API token by ID.
//
// PUT /api/v1/tokens/{token_id}
func (UnimplementedHandler) UpdateToken(ctx context.Context, req *ApiTokenUpdate, params UpdateTokenParams) (r UpdateTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}
