relations:
  - relation: PART_OF
    source:
      apiVersion: entities.devgraph.ai/v1
      kind: GithubRepository
      name: go-devgraph
    target:
      apiVersion: entities.devgraph.ai/v1
      kind: Workstream
      name: devgraph
